FROM ubuntu:latest

# Install SSH server and sudo
RUN apt-get update && apt-get install -y openssh-server sudo
RUN mkdir /var/run/sshd

# Expose SSH port
EXPOSE 22

# Copy custom entrypoint script
COPY ./test_ssh_container/ubuntu.entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Specify the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]