---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podsnservices-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "services", "services/status", "secrets"]
  verbs: ["list", "create", "delete", "get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podsnservices-sa
  namespace: ${NAMESPACE} # Namespace placeholder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podsnservices-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: podsnservices-sa
  namespace: ${NAMESPACE} # Namespace placeholder
roleRef:
  kind: ClusterRole
  name: podsnservices-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-ssh-development
  namespace: ${NAMESPACE}
  labels:
    app: socket-ssh-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-ssh-development
  template:
    metadata:
      labels:
        app: socket-ssh-development
    spec:
      serviceAccountName: podsnservices-sa
      containers:
      - name: socket-ssh-development
        image: ${REPO_NAME}/socket-ssh-development:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 9229  # Node.js debug port
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: REDIS_HOST
          value: "${REDIS_HOST}"
        - name: REDIS_PORT
          value: "${REDIS_PORT}"
        - name: REDIS_USERNAME
          value: "${REDIS_USERNAME}"
        - name: REDIS_PASSWORD
          value: "${REDIS_PASSWORD}"
        - name: REDIS_DB
          value: "${REDIS_DB}"
        - name: ALLOWED_ORIGINS
          value: "${ALLOWED_ORIGINS_DEV}"
        volumeMounts:
        - name: app-code
          mountPath: /app
      volumes:
      - name: app-code
        hostPath:
          path: ${HOSTPATH}
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: socket-ssh-development-service
  namespace: ${NAMESPACE} # Namespace placeholder
spec:
  selector:
    app: socket-ssh-development
  ports:
    - name: http
      protocol: TCP
      port: 8000     # The port exposed by the service
      targetPort: 8000  # The container's port
    - name: debug
      protocol: TCP
      port: 9229     # Node.js debug port
      targetPort: 9229
  type: ClusterIP  # Use LoadBalancer or NodePort if external access is needed
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socket-ssh-development-ingress
  namespace: ${NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: ${SOCKET_SSH_HOST}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: socket-ssh-development-service
            port:
              number: 8000
